2024-07-13 10:40:08 [INFO] validator_excel_main_class-2 - start line 136: IBRDEV-I-0000001:起動しました
2024-07-13 10:40:09 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-07-13 10:40:09 [DEBUG] common_utils - read_excel_one_sheet line 99: 
Sheet_name: Sheet1
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-07-13 10:40:09 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | NO        | int64  |
|  1 | あ        | object |
|  2 | い        | object |
|  3 | う        | int64  |
|  4 | え        | object |
|  5 | お        | object |
|  6 | か        | int64  |
|  7 | き        | object |
|  8 | く        | int64  |
|  9 | け        | int64  |
| 10 | こ        | int64  |:
2024-07-13 10:40:09 [INFO] validator_excel_main_class-2 - _log_dataframe_info line 66: DataFrame info:
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | NO        | int64  |
|  1 | あ        | object |
|  2 | い        | object |
|  3 | う        | int64  |
|  4 | え        | object |
|  5 | お        | object |
|  6 | か        | int64  |
|  7 | き        | object |
|  8 | く        | int64  |
|  9 | け        | int64  |
| 10 | こ        | int64  |:
2024-07-13 10:40:09 [WARNING] validator_utils - log_errors line 31: Validation error at row 0: {'type': 'int_type', 'loc': ('お',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-07-13 10:40:09 [WARNING] validator_utils - log_errors line 31: Validation error at row 0: {'type': 'string_type', 'loc': ('き',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}:
2024-07-13 10:40:09 [WARNING] validator_utils - log_errors line 31: Validation error at row 1: {'type': 'int_type', 'loc': ('え',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-07-13 10:40:09 [WARNING] validator_excel_main_class-2 - start line 142: Process completed with 2 validation errors:
2024-07-13 10:40:09 [INFO] validator_excel_main_class-2 - start line 152: IBRDEV-I-0000002:正常終了しました
