2024-01-03 17:30:17 [INFO] validator_excel_main_class - start line 137: IBRDEV-I-0000001:起動しました
2024-01-03 17:30:18 [ERROR] common_utils - tabulate_dataframe line 46: DataFrame.colums: Index(['index', 0], dtype='object'):
2024-01-03 17:30:18 [ERROR] common_utils - tabulate_dataframe line 47: headers: ['Columns', 'Type']:
2024-01-03 17:30:18 [ERROR] common_utils - tabulate_dataframe line 49: DataFrame.columnsとheadersは一致している必要があります:
2024-01-03 17:30:18 [ERROR] validator_excel_main_class - start line 150: Traceback (most recent call last):
  File "/developer/library_dev/project_1/src/package/validator_excel_main_class/__main__.py", line 143, in start
    _df = self._excel_to_dataframe()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/developer/library_dev/project_1/src/package/validator_excel_main_class/__main__.py", line 98, in _excel_to_dataframe
    self._log_msg(f"\n{tabulate_dataframe(_df.dtypes.reset_index(), headers=['Columns', 'Type'])}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/developer/library_dev/project_1/src/lib/common_utils/ibr_dataframe_helper.py", line 50, in tabulate_dataframe
    raise ValueError(msg)
ValueError: DataFrame.columnsとheadersは一致している必要があります
:
2024-01-03 17:32:09 [INFO] validator_excel_main_class - start line 137: IBRDEV-I-0000001:起動しました
2024-01-03 17:32:09 [DEBUG] common_utils - tabulate_dataframe line 63: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | int64  |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-01-03 17:32:09 [INFO] validator_excel_main_class - _excel_to_dataframe line 98: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | int64  |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-01-03 17:32:09 [INFO] validator_excel_main_class - _valdate line 127: 検証対象ファイル: src/share/receive/input_data_validator.xlsx:
2024-01-03 17:32:09 [INFO] validator_excel_main_class - _valdate line 128: 検証対象Sheet: Sheet1:
2024-01-03 17:32:09 [WARNING] validator_excel_main_class - _valdate line 129: vakidate error 検出件数: 2:
2024-01-03 17:32:09 [ERROR] common_utils - logger_validation_errors line 156: Validation error at (1, g):  Input should be a valid string, wrong values: 1:
2024-01-03 17:32:09 [ERROR] common_utils - logger_validation_errors line 156: Validation error at (2, d):  Input should be a valid integer, wrong values: s:
2024-01-03 17:32:09 [INFO] validator_excel_main_class - start line 153: IBRDEV-I-0000002:終了しました
2024-01-03 17:33:37 [INFO] validator_excel_main_class - start line 137: IBRDEV-I-0000001:起動しました
2024-01-03 17:33:37 [DEBUG] common_utils - tabulate_dataframe line 63: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | int64  |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-01-03 17:33:37 [INFO] validator_excel_main_class - _excel_to_dataframe line 98: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | int64  |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-01-03 17:33:37 [INFO] validator_excel_main_class - _valdate line 127: 検証対象ファイル: src/share/receive/input_data_validator.xlsx:
2024-01-03 17:33:37 [INFO] validator_excel_main_class - _valdate line 128: 検証対象Sheet: Sheet1:
2024-01-03 17:33:37 [WARNING] validator_excel_main_class - _valdate line 129: vakidate error 検出件数: 2:
2024-01-03 17:33:37 [ERROR] common_utils - logger_validation_errors line 156: Validation error at (1, g):  Input should be a valid string, wrong values: 1:
2024-01-03 17:33:37 [ERROR] common_utils - logger_validation_errors line 156: Validation error at (2, d):  Input should be a valid integer, wrong values: s:
2024-01-03 17:33:37 [INFO] validator_excel_main_class - start line 153: IBRDEV-I-0000002:終了しました
